// Generated file. Do not edit. Run `npm run precache`.
//
// The classic-script twin of precache-manifest.js, for a service worker that
// is registered without { type: 'module' }:
//
//   importScripts('app/precache-manifest.classic.js');
//   self.PRECACHE.map(function (p) { return new URL(p, self.location).href; });

self.PRECACHE_VERSION = 'pt-357f04ad02af';

self.PRECACHE = [
  'app/actionbar.css',
  'app/actionbar.js',
  'app/art.js',
  'app/artefact.css',
  'app/artefact.js',
  'app/atlas.js',
  'app/camera.js',
  'app/gear.js',
  'app/glyphgl.js',
  'app/icon-192.png',
  'app/icon-512.png',
  'app/icon-maskable-512.png',
  'app/icon.svg',
  'app/main.js',
  'app/mock.js',
  'app/motion.js',
  'app/offline.js',
  'app/photopicker.js',
  'app/pipeline.js',
  'app/precache-manifest.classic.js',
  'app/precache-manifest.js',
  'app/recents.js',
  'app/router.js',
  'app/screen.js',
  'app/screens/capture.css',
  'app/screens/capture.js',
  'app/screens/charsets.js',
  'app/screens/compose.css',
  'app/screens/compose.js',
  'app/screens/index.js',
  'app/screens/paste.css',
  'app/screens/paste.js',
  'app/screens/settings.css',
  'app/screens/settings.js',
  'app/screens/size-test.js',
  'app/shell.css',
  'app/sizeslider.css',
  'app/sizeslider.js',
  'app/state.js',
  'app/stylegesture.js',
  'app/stylerow.css',
  'app/stylerow.js',
  'app/thumb.js',
  'app/thumbstrip.css',
  'app/thumbstrip.js',
  'app/tokens.css',
  'app/viewfinder.js',
  'app/words.js',
  'index.html',
  'manifest.webmanifest',
  'src/calibrate.js',
  'src/cells.js',
  'src/constants.js',
  'src/encode.js',
  'src/fit.js',
  'src/lint.js',
  'src/metrics.js',
  'src/sizing.js',
  'src/styles.js',
  'src/tone.js',
  'src/wire.js',
  'src/wrap.js',
];
